version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: